#!/usr/bin/perl
use strict;
use warnings;
use File::Temp qw/tempdir/;

my $rc = 0;
sub ok($) {
	print "ok ", $_[0], "\n";
}
sub notok($) {
	print "not ok ", $_[0], "\n";
	$rc = 1;
}

sub str2hex($) {
	my $x = '';
	for (split //, $_[0]) {
		$x .= sprintf "%02x", ord($_);
	}
	$x .= '00';
	return $x;
}

sub hexify($) {
	$_[0] =~ s/\((.*?)\)/str2hex($1)/eg;
	$_[0] =~ s/\s+//g;
	return pack("H*", $_[0]);
}

my $WORKSPACE = tempdir(CLEANUP => 1);

sub msg_in($$$) {
	my ($test, $in, $want) = @_;
	open my $fh, ">", "$WORKSPACE/in"; print $fh hexify($in); close $fh;

	my $out = qx(./t/contract/r/msg-in <$WORKSPACE/in 2>&1);
	if ($out ne $want) {
		notok "${test} - output did not match expected:";
		open $fh, ">", "$WORKSPACE/got";  print $fh "GOT\n";    print $fh $out;  close $fh;
		open $fh, ">", "$WORKSPACE/want"; print $fh "WANTED\n"; print $fh $want; close $fh;
		print qx(diff -y $WORKSPACE/got $WORKSPACE/want 2>&1);
	} else {
		ok "${test}";
	}
}

qx(./t/contract/r/msg-acc 2>&1);
if ($? == 0) {
	ok "msg struct accessors are good";
} else {
	notok "msg-acc test program failed";
}

msg_in "[HEARTBEAT] message (0)",
       #------------------------------------------------
       "1 0 00 0000".                 # header
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of measurement
       "8 008   88aa bbcc ddee ff00". # UINT/8     number of messages transmitted
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  0 [HEARTBEAT]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0000 (00000000 00000000b)\n".
       "frames:  2\n".
       "    0) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    1) UINT/8   9847890023770160896\n".
       "";

msg_in "[SUBMIT] SAMPLE message (1/1)",
       #------------------------------------------------
       "1 1 00 0001".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of SAMPLE
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of measurement(s)
       "1 008   4093 4a45 84f4 c6e7". # FLOAT/8    first measurement
       "9 008   42a8 8eec c000 0000". # FLOAT/8    second measurement
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  1 [SUBMIT]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0001 (00000000 00000001b)\n".
       "          - SAMPLE (0001)\n".
       "frames:  4\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) FLOAT/8  1.234568e+03\n".
       "    3) FLOAT/8  1.350107e+13\n".
       "";

msg_in "[SUBMIT] TALLY message (1/2)",
       #------------------------------------------------
       "1 1 00 0002".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of TALLY
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of measurement
       "8 008   2222 4444 5555 6666". # UINT/8     increment value
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  1 [SUBMIT]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0002 (00000000 00000010b)\n".
       "          - TALLY  (0002)\n".
       "frames:  3\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) UINT/8   2459603406777837158\n".
       "";

msg_in "[SUBMIT] DELTA message (1/4)",
       #------------------------------------------------
       "1 1 00 0004".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of DELTA
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of measurement
       "9 008   4093 4a45 84f4 c6e7". # FLOAT/8    current value
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  1 [SUBMIT]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0004 (00000000 00000100b)\n".
       "          - DELTA  (0004)\n".
       "frames:  3\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) FLOAT/8  1.234568e+03\n".
       "";

msg_in "[SUBMIT] STATE message (1/8)",
       #------------------------------------------------
       "1 1 02 0008".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of STATE
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of measurement
       "0 004   0123 4567".           # UINT/8     check interval (ms)
       "a 00a   (went down)".         # STRING/*   summary
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  1 [SUBMIT]\n".
       "flags:   02 (00000010b)\n".
       "payload: 0008 (00000000 00001000b)\n".
       "          - STATE  (0008)\n".
       "frames:  4\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) UINT/4   19088743\n".
       "    3) STRING/10 \"went down\"\n".
       "";

msg_in "[SUBMIT] EVENT message (1/16)",
       #------------------------------------------------
       "1 1 00 0010".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of EVENT
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of occurrence
       "a 00a   (went down)".         # STRING/*   event description
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  1 [SUBMIT]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0010 (00000000 00010000b)\n".
       "          - EVENT  (0010)\n".
       "frames:  3\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) STRING/10 \"went down\"\n".
       "";

msg_in "[SUBMIT] FACT message (1/32)",
       #------------------------------------------------
       "1 1 00 0020".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of FACT
       "a 00a   (host.fqdn)".         # STRING/*   fact value
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  1 [SUBMIT]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0020 (00000000 00100000b)\n".
       "          - FACT   (0020)\n".
       "frames:  2\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) STRING/10 \"host.fqdn\"\n".
       "";

msg_in "[BROADCAST] SAMPLE message (2/1)",
       #------------------------------------------------
       "1 2 00 0001".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of SAMPLE
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   start of aggregation window
       "0 004   0123 4567".           # UINT/4     aggregation window length
       "1 008   408a acce dfe7 5bc4". # FLOAT/8    measurement
       "1 008   42a8 8eec c000 0000". # FLOAT/8    measurement
       "9 008   408a acce dfe7 5bc4". # FLOAT/8    measurement
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0001 (00000000 00000001b)\n".
       "          - SAMPLE (0001)\n".
       "frames:  6\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) UINT/4   19088743\n".
       "    3) FLOAT/8  8.536010e+02\n".
       "    4) FLOAT/8  1.350107e+13\n".
       "    5) FLOAT/8  8.536010e+02\n".
       "";

msg_in "[BROADCAST] TALLY message (2/2)",
       #------------------------------------------------
       "1 2 00 0002".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of TALLY
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   start of aggregation window
       "0 004   0123 4567".           # UINT/4     aggregation window length
       "8 008   0011 2233 4455 6677". # UINT/8     tallied value
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0002 (00000000 00000010b)\n".
       "          - TALLY  (0002)\n".
       "frames:  4\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) UINT/4   19088743\n".
       "    3) UINT/8   4822678189205111\n".
       "";

msg_in "[BROADCAST] DELTA message (2/4)",
       #------------------------------------------------
       "1 2 00 0004".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of DELTA
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   start of aggregation window
       "0 004   0123 4567".           # UINT/4     aggregation window length
       "9 008   408a acce dfe7 5bc4". # FLOAT/8    calculated rate of change
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0004 (00000000 00000100b)\n".
       "          - DELTA  (0004)\n".
       "frames:  4\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) UINT/4   19088743\n".
       "    3) FLOAT/8  8.536010e+02\n".
       "";

msg_in "[BROADCAST] STATE message (2/8)",
       #------------------------------------------------
       "1 2 80 0008".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of STATE
       "0 004   4321 1234".           # UINT/4     freshness window (ms)
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of check (current state)
       "a 00f   (nothing broken)".    # STRING/*   summary message (current state)
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   80 (10000000b)\n".
       "payload: 0008 (00000000 00001000b)\n".
       "          - STATE  (0008)\n".
       "frames:  4\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) UINT/4   1126240820\n".
       "    2) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    3) STRING/15 \"nothing broken\"\n".
       "";

msg_in "[BROADCAST] STATE transitional message (2/8)",
       #------------------------------------------------
       "1 2 c4 0008".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of STATE
       "0 004   4321 1234".           # UINT/4     freshness window (ms)
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of check (previous state)
       "2 010   (it recovered...)".   # STRING/*   summary message (previous state)
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of check (current state)
       "a 010   (it recovered...)".   # STRING/*   summary message (current state)
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   c4 (11000100b)\n".
       "payload: 0008 (00000000 00001000b)\n".
       "          - STATE  (0008)\n".
       "frames:  6\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) UINT/4   1126240820\n".
       "    2) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    3) STRING/16 \"it recovered...\"\n".
       "    4) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    5) STRING/16 \"it recovered...\"\n".
       "";

msg_in "[BROADCAST] EVENT message (2/16)",
       #------------------------------------------------
       "1 2 00 0010".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of EVENT
       "6 008   0000 0000 5921 e9e2". # TSTAMP/8   time of occurrence
       "a 00f   (stuff's broken)".    # STRING/*   event description
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0010 (00000000 00010000b)\n".
       "          - EVENT  (0010)\n".
       "frames:  3\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) TSTAMP/8 [Sun May 21 19:26:26 2017] (1495394786)\n".
       "    2) STRING/15 \"stuff's broken\"\n".
       "";

msg_in "[BROADCAST] FACT message (2/32)",
       #------------------------------------------------
       "1 2 00 0020".                 # header
       "2 008   (a=b,c=d)".           # STRING/*   qualified name of FACT
       "a 00f   (value of fact!)".    # STRING/*   fact value
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  2 [BROADCAST]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0020 (00000000 00100000b)\n".
       "          - FACT   (0020)\n".
       "frames:  2\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "    1) STRING/15 \"value of fact!\"\n".
       "";

msg_in "[FORGET] message (3)",
       #------------------------------------------------
       "1 3 00 0007".                 # header
       "a 008   (a=b,c=d)".           # STRING/*   qualified name pattern
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  3 [FORGET]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0007 (00000000 00000111b)\n".
       "          - SAMPLE (0001)\n".
       "          - TALLY  (0002)\n".
       "          - DELTA  (0004)\n".
       "frames:  1\n".
       "    0) STRING/8 \"a=b,c=d\"\n".
       "";

msg_in "[REPLAY] message (4)",
       #------------------------------------------------
       "1 4 00 0007".                 # header
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  4 [REPLAY]\n".
       "flags:   00 (00000000b)\n".
       "payload: 0007 (00000000 00000111b)\n".
       "          - SAMPLE (0001)\n".
       "          - TALLY  (0002)\n".
       "          - DELTA  (0004)\n".
       "frames:  0\n".
       "";

msg_in "[SUBSCRIBE] message (5)",
       #------------------------------------------------
       "1 5 03 0006".                 # header
       "a 008   (a=b,c=*)".           # STRING/*   qualified name pattern
       "",
       #------------------------------------------------
       "version: 1\n".
       "opcode:  5 [SUBSCRIBE]\n".
       "flags:   03 (00000011b)\n".
       "payload: 0006 (00000000 00000110b)\n".
       "          - TALLY  (0002)\n".
       "          - DELTA  (0004)\n".
       "frames:  1\n".
       "    0) STRING/8 \"a=b,c=*\"\n".
       "";

msg_in "[INVALID] short buffer",
       #------------------------------------------------
       "00",
       #------------------------------------------------
       "malformed message\n".
       "";

my $got = qx(./t/contract/r/msg-out 2>&1);
my $exit = $?;
my $want = <<EOF;
---
 10 55 00 03 70 00 a0 04 74 65 73 74

+++
version: 1
opcode:  0 [HEARTBEAT]
flags:   55 (01010101b)
payload: 0003 (00000000 00000011b)
          - SAMPLE (0001)
          - TALLY  (0002)
frames:  2
    0) NIL/0
    1) STRING/4 "test"


---
 15 14 00 00 00 02 12 34 00 04 de ad be ef 00 08
 de ca fb ad ab ad 1d ea 10 04 3f 9e 04 19 10 08
 41 1b e1 54 7e 6b 74 dd 20 00 20 04 68 69 79 61
 20 0c 68 65 6c 6c 6f 2c 20 77 6f 72 6c 64 60 08
 11 22 33 44 55 66 77 88 70 00 f0 00

+++
version: 1
opcode:  5 [SUBSCRIBE]
flags:   14 (00010100b)
payload: 0000 (00000000 00000000b)
frames:  11
    0) UINT/2   4660
    1) UINT/4   3735928559
    2) UINT/8   16053920545043717610
    3) FLOAT/4  1.234500e+00
    4) FLOAT/8  4.567891e+05
    5) STRING/0 ""
    6) STRING/4 "hiya"
    7) STRING/12 "hello, world"
    8) TSTAMP/8  (1234605616436508552)
    9) NIL/0
    10) NIL/0


---
 13 42 00 18 f0 00

+++
version: 1
opcode:  3 [FORGET]
flags:   42 (01000010b)
payload: 0018 (00000000 00011000b)
          - STATE  (0008)
          - EVENT  (0010)
frames:  1
    0) NIL/0


EOF
if ($exit == 0) {
	if ($got ne $want) {
		my $fh;
		notok "message wire formatting failed";
		open $fh, ">", "$WORKSPACE/got";  print $fh "GOT\n$got";   close $fh;
		open $fh, ">", "$WORKSPACE/want"; print $fh "WANT\n$want"; close $fh;
		print qx(diff -y $WORKSPACE/got $WORKSPACE/want 2>&1);
	} else {
		ok "message wire formatting is ok";
	}
} else {
	notok "message wire formatting failed; exited $exit";
}

exit $rc;
